---
output: html_document
---

  
### Day 1 "Big data in Biogeography"
  
-	9:30 Welcome & Introduction 

- 9:45 Presentation of participants, forming of teams

-	10:30 Lecture: Big data in Biogeography

-	11:30 Questions, final computer set up when necessary

- 13:00 Group work and literature discussion

- 15:00 Project definition

- 15:30 Lecture & Hands on "Biodiversity databases"


### Day 2 "Recent biogeography"

- 9:30 Lecture “Common biases, caveats and errors in biodiversity databases”

- 10:00 Lecture and Hands on exercise “Novel tools in biogeography: bioregionalization, automated conservation assessment, species to area classification” 

- 13:00 Hands-on: Project work recent biogeography

- 15:15 Lecture: Biogeography through time, combining distribution ranges and phylogenies 

- 16:00 Demos & exercise Bioogeography and Phylogenies (`BioGeoBEARS`, `DEC`)


### Day 3 "Historical Biogeography"

- 9:30 Lecture historical biogeography – modeling the evolution of geographic ranges as a continuous trait (`JIVE`, `fossilBM`)

- 11:30	 Hands on historical biogeography/group work 


### Day 4 "Fossil Biogeography"

- 9:30	Modeling geographic range evolution using the fossil record (`DES` model)

- 11:30 Guest lecture by Sara Varela (Museum für Naturkunde) as Species distribution models to work in paleobiogeography

Afternoon: Hands on fossils in biogeography 


### Day 5, "Putting it all together"

- 09:30 Demo & exercise "Visualization of the results in R"

- 11:00 Project work

- 13:30 Student presentation and examination

- 15:00 Course evaluation and wrap up
