---
output: html_document
---

## Day 1 "Big data in Biogeography"

-	Welcome & Introduction 

- Presentation of participants (3 - 5 minutes each, three slides)

-	Introductory lecture: Recent developments in big data biogeography

- Literature group work and discussion 

- Lecture & Hands on "Biodiversity databases"

- Definition of student projects


## Day 2 "Biogeography through space - Recent biodiversity patterns"

- Lecture “Common biases, caveats and errors in biodiversity databases and tools to dress them”

- Hands-on "Recent biodiversity patterns" in R (Obtaining occurrence records, data cleaning, exploring sampling bias)

- Lecture “Novel tools for big data biogeography: bioregionalization, automated conservation assessment, species to area classification” 

- Hands-on: "Recent biogeography" (Species richness, endemism, taxon-specific bioregionalization, extracting environmental data)

- Optional lecture on a topic chose by the participants (Bayesian methods or Diversification rate analyses)


## Day 3 "Temporal biogeography - reconstructing ancestral ranges"

- Lecture "Historical biogeography – methods to model the evolution of geographic ranges through time"

- Hands-on "Reconstructing ancestral ranges" (`DEC`, `BioGeoBEARS`, `Biogeographic stochastic mapping`, `GeoSSE`)

- Lecture "Trait evolution"

- Hands on "Reconstructing ancestral ranges as continuous trait" (`BITE`)


## Day 4 "Fossil Biogeography"

- Lecture "Fossil biogeography"

- Hands-on Fossil biogeography (`fossilBM`)

- Guest lecture by [Sara Varela](https://scholar.google.de/citations?hl=de&user=8dckI70AAAAJ) on Species distribution in paleobiogeography

- Lecture "The DES model - A new approach to estimate area connectivity and diversification rates" (`DES`)

- Time for project work


## Day 5, "Putting it all together"

- Hands-on "Visualizing biogeographic results in R"

- Work on student project and presentation

- Student presentations

- Course evaluation and wrap up
